### ISSUE TITLE
[Internal] Create GitHub templates for issues & pull requests

### ISSUE THREAD

**Issue by harshasrikara** [OctoPipeline/OctoPipeline-Frontend#1]
### Overview
To better format our work create templates that will be used for creating future issues & pull requests.

### Task List
 - [ ] Templates for Issues
 - [ ] Templates for Pull Requests
 - [ ] Duplicate templates into [OctoPipeline-Backend](https://github.com/OctoPipeline/OctoPipeline-Backend)

### Additional Context
Feel free to use the minimalist structure of this GitHub issue (3 sections --> overview, task list & additional context) as the template.
Github Documentation --> [Configuring issue templates for your repository](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/configuring-issue-templates-for-your-repository)
